# Generated by Django 5.2.6 on 2025-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0003_livequizsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
