# Generated by Django 5.2.6 on 2025-11-14 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pdf_file', models.FileField(upload_to='pdf_analysis/temp/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('extracted_text', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Document',
                'verbose_name_plural': 'Analysis Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task', models.CharField(choices=[('summarize', 'Summarize'), ('explain', 'Explain'), ('answer', 'Answer')], max_length=20)),
                ('task_options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('cost_estimate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='pdf_analyzer.analysisdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
